<?php
return array (
  'title' => '美国',
  'style' => '0',
  'siteid' => '0',
  'data' => 
  array (
    3603 => 
    array (
      'linkageid' => '3603',
      'name' => 'Alabama',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3603',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '阿拉巴马州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3604 => 
    array (
      'linkageid' => '3604',
      'name' => 'Alaska',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3604',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '阿拉斯加州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3605 => 
    array (
      'linkageid' => '3605',
      'name' => 'Arizona',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3605',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '阿利桑那州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3606 => 
    array (
      'linkageid' => '3606',
      'name' => 'Arkansas',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3606',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '阿肯色州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3607 => 
    array (
      'linkageid' => '3607',
      'name' => 'California',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3607',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '加利福尼亚州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3608 => 
    array (
      'linkageid' => '3608',
      'name' => 'Colorado',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3608',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '科罗拉多州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3609 => 
    array (
      'linkageid' => '3609',
      'name' => 'Connecticut',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3609',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '康涅狄格州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3610 => 
    array (
      'linkageid' => '3610',
      'name' => 'Delaware',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3610',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '特拉华州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3611 => 
    array (
      'linkageid' => '3611',
      'name' => 'Florida',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3611',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '佛罗里达州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3612 => 
    array (
      'linkageid' => '3612',
      'name' => 'Georgia',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3612',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '乔治亚州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3613 => 
    array (
      'linkageid' => '3613',
      'name' => 'Hawaii',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3613',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '夏威夷州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3614 => 
    array (
      'linkageid' => '3614',
      'name' => 'Idaho',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3614',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '爱达荷州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3615 => 
    array (
      'linkageid' => '3615',
      'name' => 'Illinois',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3615',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '伊利诺斯州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3616 => 
    array (
      'linkageid' => '3616',
      'name' => 'Indiana',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3616',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '印第安纳州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3617 => 
    array (
      'linkageid' => '3617',
      'name' => 'Iowa',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3617',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '爱荷华州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3618 => 
    array (
      'linkageid' => '3618',
      'name' => 'Kansas',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3618',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '堪萨斯州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3619 => 
    array (
      'linkageid' => '3619',
      'name' => 'Kentucky',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3619',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '肯塔基州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3620 => 
    array (
      'linkageid' => '3620',
      'name' => 'Louisiana',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3620',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '路易斯安那州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3621 => 
    array (
      'linkageid' => '3621',
      'name' => 'Maine',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3621',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '缅因州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3622 => 
    array (
      'linkageid' => '3622',
      'name' => 'Maryland',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3622',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '马里兰州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3623 => 
    array (
      'linkageid' => '3623',
      'name' => 'Massachusetts',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3623',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '马萨诸塞州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3624 => 
    array (
      'linkageid' => '3624',
      'name' => 'Michigan',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3624',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '密歇根州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3625 => 
    array (
      'linkageid' => '3625',
      'name' => 'Minnesota',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3625',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '明尼苏达州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3626 => 
    array (
      'linkageid' => '3626',
      'name' => 'Mississippi',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3626',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '密西西比州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3627 => 
    array (
      'linkageid' => '3627',
      'name' => 'Missouri',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3627',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '密苏里州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3628 => 
    array (
      'linkageid' => '3628',
      'name' => 'Montana',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3628',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '蒙大拿州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3629 => 
    array (
      'linkageid' => '3629',
      'name' => 'Nebraska',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3629',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '内布拉斯加州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3630 => 
    array (
      'linkageid' => '3630',
      'name' => 'Nevada',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3630',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '内华达州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3631 => 
    array (
      'linkageid' => '3631',
      'name' => 'New hampshire',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3631',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '新罕布什尔州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3632 => 
    array (
      'linkageid' => '3632',
      'name' => 'New jersey',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3632',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '新泽西州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3633 => 
    array (
      'linkageid' => '3633',
      'name' => 'New mexico',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3633',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '新墨西哥州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3634 => 
    array (
      'linkageid' => '3634',
      'name' => 'New York',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3634',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '纽约州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3635 => 
    array (
      'linkageid' => '3635',
      'name' => 'North Carolina',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3635',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '北卡罗来纳州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3636 => 
    array (
      'linkageid' => '3636',
      'name' => 'North Dakota',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3636',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '北达科他州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3637 => 
    array (
      'linkageid' => '3637',
      'name' => 'Ohio',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3637',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '俄亥俄州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3638 => 
    array (
      'linkageid' => '3638',
      'name' => 'Oklahoma',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3638',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '俄克拉荷马州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3639 => 
    array (
      'linkageid' => '3639',
      'name' => 'Oregon',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3639',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '俄勒冈州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3640 => 
    array (
      'linkageid' => '3640',
      'name' => 'Pennsylvania',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3640',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '宾夕法尼亚州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3641 => 
    array (
      'linkageid' => '3641',
      'name' => 'Rhode island',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3641',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '罗得岛州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3642 => 
    array (
      'linkageid' => '3642',
      'name' => 'South carolina',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3642',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '南卡罗来纳州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3643 => 
    array (
      'linkageid' => '3643',
      'name' => 'South dakota',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3643',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '南达科他州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3644 => 
    array (
      'linkageid' => '3644',
      'name' => 'Tennessee',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3644',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '田纳西州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3645 => 
    array (
      'linkageid' => '3645',
      'name' => 'Texas',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3645',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '得克萨斯州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3646 => 
    array (
      'linkageid' => '3646',
      'name' => 'Utah',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3646',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '犹他州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3647 => 
    array (
      'linkageid' => '3647',
      'name' => 'Vermont',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3647',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '佛蒙特州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3648 => 
    array (
      'linkageid' => '3648',
      'name' => 'Virginia',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3648',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '弗吉尼亚州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3649 => 
    array (
      'linkageid' => '3649',
      'name' => 'Washington',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3649',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '华盛顿州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3650 => 
    array (
      'linkageid' => '3650',
      'name' => 'West Virginia',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3650',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '西弗吉尼亚州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3651 => 
    array (
      'linkageid' => '3651',
      'name' => 'Wisconsin',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3651',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '威斯康辛州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3652 => 
    array (
      'linkageid' => '3652',
      'name' => 'Wyoming',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3652',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '怀俄明州',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3653 => 
    array (
      'linkageid' => '3653',
      'name' => 'Washington, D.C',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3653',
      'keyid' => '3654',
      'listorder' => '0',
      'description' => '华盛顿哥伦比亚特区',
      'setting' => NULL,
      'siteid' => '0',
    ),
  ),
);
?>