<?php
return array (
  'title' => '案例分类By Industry',
  'style' => '0',
  'siteid' => '0',
  'data' => 
  array (
    3906 => 
    array (
      'linkageid' => '3906',
      'name' => 'Finance',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3906',
      'keyid' => '3904',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3907 => 
    array (
      'linkageid' => '3907',
      'name' => 'Education',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3907',
      'keyid' => '3904',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3908 => 
    array (
      'linkageid' => '3908',
      'name' => 'Insurance',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3908',
      'keyid' => '3904',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3909 => 
    array (
      'linkageid' => '3909',
      'name' => 'Manufacturing',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3909',
      'keyid' => '3904',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3910 => 
    array (
      'linkageid' => '3910',
      'name' => 'SMB',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3910',
      'keyid' => '3904',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3911 => 
    array (
      'linkageid' => '3911',
      'name' => 'Government',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3911',
      'keyid' => '3904',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3912 => 
    array (
      'linkageid' => '3912',
      'name' => 'Retail',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3912',
      'keyid' => '3904',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3913 => 
    array (
      'linkageid' => '3913',
      'name' => 'Enterprises',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3913',
      'keyid' => '3904',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3914 => 
    array (
      'linkageid' => '3914',
      'name' => 'Healthcare',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3914',
      'keyid' => '3904',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3915 => 
    array (
      'linkageid' => '3915',
      'name' => 'Energy',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3915',
      'keyid' => '3904',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
  ),
);
?>