<?php
return array (
  12 => 
  array (
    'catid' => '12',
    'siteid' => '1',
    'type' => '1',
    'modelid' => '0',
    'parentid' => '6',
    'arrparentid' => '0,6',
    'child' => '0',
    'arrchildid' => '12',
    'catname' => 'About Centerm',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'COMPANY/',
    'catdir' => 'about_centerm',
    'url' => 'http://127.0.0.1:9065/index.php?m=content&c=index&a=lists&catid=12',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"ishtml":"0","template_list":"default","page_template":"page_about_centerm","meta_title":"","meta_keywords":"","meta_description":"","category_ruleid":"6","show_ruleid":"","repeatchargedays":"1"}',
    'listorder' => '1',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'about centerm',
    'usable_type' => '',
    'create_to_html_root' => NULL,
    'ishtml' => '0',
    'content_ishtml' => NULL,
    'category_ruleid' => '6',
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
  13 => 
  array (
    'catid' => '13',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '6',
    'arrparentid' => '0,6',
    'child' => '0',
    'arrchildid' => '13',
    'catname' => 'Newsroom',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'COMPANY/',
    'catdir' => 'newsroom',
    'url' => 'http://127.0.0.1:9065/index.php?m=content&c=index&a=lists&catid=13',
    'items' => '1',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '2',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'newsroom',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  14 => 
  array (
    'catid' => '14',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '6',
    'arrparentid' => '0,6',
    'child' => '0',
    'arrchildid' => '14',
    'catname' => 'Events',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'COMPANY/',
    'catdir' => 'events',
    'url' => 'http://127.0.0.1:9065/index.php?m=content&c=index&a=lists&catid=14',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '3',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'events',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  15 => 
  array (
    'catid' => '15',
    'siteid' => '1',
    'type' => '2',
    'modelid' => '0',
    'parentid' => '6',
    'arrparentid' => '',
    'child' => '0',
    'arrchildid' => '',
    'catname' => 'Contact',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => '',
    'url' => 'http://127.0.0.1:9065/index.php?m=content&c=index&a=lists&catid=11',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"show_ruleid":"","repeatchargedays":"1"}',
    'listorder' => '4',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'contact',
    'usable_type' => '',
    'create_to_html_root' => NULL,
    'ishtml' => NULL,
    'content_ishtml' => NULL,
    'category_ruleid' => NULL,
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
  6 => 
  array (
    'catid' => '6',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '6,12,13,14,15',
    'catname' => 'COMPANY',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'COMPANY',
    'url' => 'http://127.0.0.1:9065/index.php?m=content&c=index&a=lists&catid=6',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '6',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'company',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  7 => 
  array (
    'catid' => '7',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '7',
    'catname' => 'PRODUCT',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'PRODUCT',
    'url' => 'http://127.0.0.1:9065/index.php?m=content&c=index&a=lists&catid=7',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '7',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'product',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  8 => 
  array (
    'catid' => '8',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '8',
    'catname' => 'SOLUTION',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'SOLUTION',
    'url' => 'http://127.0.0.1:9065/index.php?m=content&c=index&a=lists&catid=8',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '8',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'solution',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  9 => 
  array (
    'catid' => '9',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '9',
    'catname' => 'SUPPORT',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'SUPPORT',
    'url' => 'http://127.0.0.1:9065/index.php?m=content&c=index&a=lists&catid=9',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '9',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'support',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  10 => 
  array (
    'catid' => '10',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '10',
    'catname' => 'PARTNER',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'PARTNER',
    'url' => 'http://127.0.0.1:9065/index.php?m=content&c=index&a=lists&catid=10',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '10',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'partner',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  11 => 
  array (
    'catid' => '11',
    'siteid' => '1',
    'type' => '1',
    'modelid' => '0',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '11',
    'catname' => 'CONTACT',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'CONTACT',
    'url' => 'http://127.0.0.1:9065/index.php?m=content&c=index&a=lists&catid=11',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"ishtml":"0","template_list":"default","page_template":"page_contact","meta_title":"","meta_keywords":"","meta_description":"","category_ruleid":"6","show_ruleid":"","repeatchargedays":"1"}',
    'listorder' => '11',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'contact',
    'usable_type' => '',
    'create_to_html_root' => NULL,
    'ishtml' => '0',
    'content_ishtml' => NULL,
    'category_ruleid' => '6',
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
);
?>