<?php
return array (
  1 => 
  array (
    'modelid' => '1',
    'siteid' => '1',
    'name' => '文章模型',
    'description' => '',
    'tablename' => 'news',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list',
    'show_template' => 'show',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  14 => 
  array (
    'modelid' => '14',
    'siteid' => '1',
    'name' => '案例模型',
    'description' => '',
    'tablename' => 'case',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list',
    'show_template' => 'show',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  15 => 
  array (
    'modelid' => '15',
    'siteid' => '1',
    'name' => '文档下载模型',
    'description' => '',
    'tablename' => 'download_file',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list',
    'show_template' => 'show',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  16 => 
  array (
    'modelid' => '16',
    'siteid' => '1',
    'name' => '软件下载模型',
    'description' => '',
    'tablename' => 'download_software',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list',
    'show_template' => 'show',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  12 => 
  array (
    'modelid' => '12',
    'siteid' => '1',
    'name' => '产品模型',
    'description' => '',
    'tablename' => 'products',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list',
    'show_template' => 'show',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  13 => 
  array (
    'modelid' => '13',
    'siteid' => '1',
    'name' => 'Events',
    'description' => '',
    'tablename' => 'events',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list',
    'show_template' => 'show',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  18 => 
  array (
    'modelid' => '18',
    'siteid' => '1',
    'name' => 'Banner',
    'description' => '',
    'tablename' => 'banner',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list',
    'show_template' => 'show',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  19 => 
  array (
    'modelid' => '19',
    'siteid' => '1',
    'name' => 'solution',
    'description' => '',
    'tablename' => 'solution',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list',
    'show_template' => 'show',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
);
?>